### PR TITLE
Fix for plugin socket location

### LINKED ISSUE #30: Assumed location of plugin sockets has changed
https://github.com/docker/docker/pull/13951

### PR DESCRIPTION
**Pull request by Telmo**
Fixes #30

### CODE REVIEW

File: plugin/main.go [hunk 1]
```diff
@@ -4,9 +4,10 @@ import (
 	"flag"
 	"fmt"
 
+	"os"
+
 	"github.com/weaveworks/docker-plugin/plugin/driver"
 	. "github.com/weaveworks/weave/common"
-	"os"
```
Comment (Telmo) [inline plugin/main.go:9]: this is gofmt doing its thing.

File: start-plugin.sh [hunk 2]
```diff
@@ -4,5 +4,5 @@ set -e
 
 docker run --name=weaveplugin --privileged -d \
     --net=host -v /var/run/docker.sock:/var/run/docker.sock \
-    -v /usr/share/docker/plugins:/usr/share/docker/plugins \
+    -v /run/docker/plugins:/usr/share/docker/plugins \
```
Comment (squaremo) [inline start-plugin.sh:7]: Should the target `/usr/share/docker/plugins` of the volume mount match the default value `/run/docker/plugins/weave.sock` for the socket from above? (I know I did not have this lined up previously)
